apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-app
        image: nginx:latest
        ports:
        - containerPort: 3306
        volumeMounts:
          - name:  sqlstorage
            mountPath:  /usr/share/nginx/html/
        # env:
        # - name:  MYSQL_ROOT_PASSWORD
        #   value: redhat
        # - name:  MYSQL_USER
        #   value: tarun
        # - name:  MYSQL_PASSWORD
        #   value: redhat
      volumes:
      - name: sqlstorage
        persistentVolumeClaim:
          claimName: mysql-storage-pvc
        