apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-storage-app
  namespace: database
  labels: 
    type: local
spec:
  selector:
    matchLabels:
      type: local
  template:
    metadata:
      labels:
        type: local
    spec:
      containers:
      - name: local-storage-app
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: storageapp
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: storageapp
          persistentVolumeClaim:
            claimName: local-pvc-claim
