kind: Service
apiVersion: v1
metadata:
  name:  local-svc
  namespace: database
spec:
  selector:
    app:  local
  type:  NodePort
  ports:
  - name:  local-port
    port:  80
    targetPort:  80
    nodePort: 31222