apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim
  namespace: database
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
