kind: Service
apiVersion: v1
metadata:
  name:  mysql-svc
  namespace: database
  labels:
    app: mysql
spec:
  selector:
    app:  mysql
  type:  NodePort
  ports:
  - name:  mysql-portport
    port:  80
    targetPort:  80
    nodePort: 31222