apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  namespace: database
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /dir/container1
    server: 172.31.32.153
