apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-pvc
  namespace: database
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce