kind: Service
apiVersion: v1
metadata:
  name:  mysql-svc
  namspace: databases
  labels:
    app: mysql
spec:
  selector:
    app:  mysql
  type:  NodePort
  ports:
  - name:  mysql-port
    port:  3306
    targetPort:  3306
    nodePort: 31999