apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:   
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-app
        image: mysql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: tarun
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
