apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-app
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
# create service for expose
kind: Service
apiVersion: v1
metadata:
  name:  myapp-svc
spec:
  selector:
    app:  myapp
  type:  NodePort
  ports:
  - name:  myapp-port
    port:  80
    targetPort:  80
    nodePort: 30004

# create svc with cluster ip

# kind: Service
# apiVersion: v1
# metadata:
#   name:  myapp-svc
# spec:
#   selector:
#     app:  myapp
#   type:  ClusterIP
#   ports:
#   - name:  http
#     port:  80
#     targetPort:  80