apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    type: infra
spec:
  containers:
  - name: apache
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  apache-svc
spec:
  selector:
    type: infra
  type:  NodePort
  ports:
  - name:  apache-port
    port:  80
    targetPort:  80
    nodePort: 30003
