apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: learning
  labels:
    name: app1
spec:
  containers:
  - name: app1
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
