apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    type: infra
spec:
  containers:
  - name: firstpod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80