apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    type: infra
spec:
  containers:
  - name: firstpod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  firstpod-svc
spec:
  selector:
    type: infra
  type: NodePort
  ports:
  - name:  firstpod -port
    port:  80
    targetPort:  80
    nodePort: 30001 # node port range is 30,000 to 32,767 only